from ubuntu:14.04

maintainer Ankit Sinha ankitsinha611@gmail.com

# Update ubuntu & Install necesarry software
RUN apt-get update && apt-get install -y \
	curl \
	git \
	python \
	python-dev \
	python-distribute \
	python-pip \
	python-virtualenv \
	supervisor \
	nginx

# Create Directories
RUN mkdir -p /home/root/apps/bitbucket_webhook \
			 /home/root/apps/production_app \
			 /home/root/apps/development_app 


# Get the hook file from github
RUN cd /home/root/apps/bitbucket_webhook && git clone https://github.com/ankitjamuar/CI-Boilerplate.git && cd CI-Boilerplate

# Install Python packages
RUN pip install uwsgi
RUN pip install -r requirements.txt
RUN sudo supervisorctl -c /home/root/apps/bitbucket_webhook/CI-Boilerplate/supervisor.conf reread
RUN sudo supervisorctl -c /home/root/apps/bitbucket_webhook/CI-Boilerplate/supervisor.conf update



# Create Directory
RUN mkdir /home/root/apps

# Install python packages
RUN pip install requiremnents.txt